# Generated by Django 4.1.6 on 2023-03-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=100)),
                ('a_password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
