# Generated by Django 4.1.6 on 2023-03-24 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_status', models.IntegerField(blank=True, default=None, null=True)),
                ('chat_sender_id', models.IntegerField()),
                ('chat_reciever_id', models.IntegerField()),
                ('chat_start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('chat_last_update', models.DateTimeField(blank=True, default=None, null=True)),
                ('chat_unread_count', models.IntegerField(blank=True, default=0, null=True)),
                ('chat_last_message_sender', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(default=None)),
                ('message_sender_id', models.IntegerField()),
                ('message_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('message_status', models.IntegerField(blank=True, default=None, null=True)),
                ('message_chat_id', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=50)),
                ('user_aboutof', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('user_status', models.IntegerField(blank=True, default=1, null=True)),
                ('user_last_seen', models.DateTimeField(blank=True, default=None, null=True)),
                ('user_online_status', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_sub', models.CharField(max_length=300)),
                ('complaint_body', models.CharField(max_length=300)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'complaints',
            },
        ),
    ]
